### ISSUE TITLE
Problems importing

### ISSUE THREAD

**Issue by Richardjmorton** [drzowie/image-noise-gate#1]
Hi, 

I am just trying to give the code a whirl but I am running into problems when trying to import to python.

```
from image_noise_gate import noisegate
-----------------------------------------------------------
ModuleNotFoundError       Traceback (most recent call last)
<ipython-input-55-cece792c5681> in <module>
----> 1 from image_noise_gate import noisegate

~/py_routines/image_noise_gate/noisegate/__init__.py in <module>
      4
      5 # Primary tools
----> 6 from .tools import *

ModuleNotFoundError: No module named 'image_noise_gate.noisegate.tools'
```

**Comment by drzowie** [comment]
Hi, Richard,

Because tools is a .pyx file, it needs to be compiled with Cython.  

You’ll need to run “python setup.py develop” from the shell — that should take care of it.

Let me know if that solves the problem!

Chers,
Craig

**Comment by Richardjmorton** [comment]
Whoops, of course! Thanks.
